### ISSUE TITLE
read sessionStorage stored value on server side

### ISSUE THREAD

**Issue by shlomit** [yckart/jquery.storage.js#1]
is it possible to read sessionstorage value on code behind?(vb)

when dropdown is changed I store selected value with sessioStorage

I need to read it on server side 

thanks!

**Comment by yckart** [comment]
You will need to pass this information from the client to the server using standard HTTP techniques. Using javascript you could fill:
- Hidden fields
- Query string parameters
- POST
- Ajax call to the server
- ...

It will all depend on how your application is organized, what kind of information is being stored, its volume, whether you want to redirect or not, ... But in all cases this should be done using javascript since that's the only way to access data stored in localStorage.
